version: "3.9"

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:4173}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000}
    depends_on:
      - backend
    ports:
      - "4173:80"
